print('Seja Bem Vindo')
print()
print('A Fast Car Oferecendo Sempre o Melhor para você')
print()
dias = int(input('Por Quantos Dias o Seu Cliente Utilizou o Veiculo ?: '))
km = float(input('Quantos Km Rodados ele Fez?: '))
pagar = (dias * 60) + (km * 0.15)
print()
print('O Seu Cliente devera pagar R${:.2f}'.format(pagar))
print()
print('Desenvolved by \033[1;31;40mLuccas Santana\033[m')